### ISSUE TITLE
Function "lessOrEqual" cannot accept missing value at position 0

### ISSUE THREAD

**Issue by liuhuanshuo** [jpmml/jpmml-evaluator-python#17]
The following error occurs when making a prediction using jpmml-evaluator in Python.

It seems that the prompt cannot handle missing value, but it is indeed predictable in my pipeline

My raw data does contain missing values, and I processed it using ExpressionTransformer. Do I need to add additional processing so that the missing values can be supported by evaluator?
```
Py4JJavaError: An error occurred while calling z:org.jpmml.evaluator.python.PythonUtil.evaluateAll.
: org.jpmml.evaluator.MissingArgumentException: Function "lessOrEqual" cannot accept missing value at position 0
	at org.jpmml.evaluator.functions.AbstractFunction.getRequiredArgument(AbstractFunction.java:101)
	at org.jpmml.evaluator.functions.AbstractFunction.getArgument(AbstractFunction.java:76)
	at org.jpmml.evaluator.functions.BinaryFunction.evaluate(BinaryFunction.java:43)
	at org.jpmml.evaluator.ExpressionUtil.evaluateFunction(ExpressionUtil.java:463)
	at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:426)
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:167)
	at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:129)
	at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:345)
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:167)
	at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:129)
	at org.jpmml.evaluator.ExpressionUtil.evaluateExpressionContainer(ExpressionUtil.java:61)
	at org.jpmml.evaluator.ExpressionUtil.evaluateTypedExpressionContainer(ExpressionUtil.java:66)
	at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:86)
	at org.jpmml.evaluator.ModelEvaluationContext.resolve(ModelEvaluationContext.java:100)
	at org.jpmml.evaluator.EvaluationContext.evaluate(EvaluationContext.java:94)
	at org.jpmml.evaluator.regression.RegressionModelEvaluator.evaluateRegressionTable(RegressionModelEvaluator.java:263)
	at org.jpmml.evaluator.regression.RegressionModelEvaluator.evaluateClassification(RegressionModelEvaluator.java:158)
	at org.jpmml.evaluator.ModelEvaluator.evaluateInternal(ModelEvaluator.java:446)
	at org.jpmml.evaluator.ModelEvaluator.evaluate(ModelEvaluator.java:300)
	at org.jpmml.evaluator.python.PythonUtil.evaluate(PythonUtil.java:92)
	at org.jpmml.evaluator.python.PythonUtil.evaluateAll(PythonUtil.java:58)
	at org.jpmml.evaluator.python.PythonUtil.evaluateAll(PythonUtil.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

JavaError                                 Traceback (most recent call last)
<ipython-input-383-f4ba64f4738e> in <module>
----> 1 evaluator.evaluateAll(x_original.head())

~/.local/lib/python3.7/site-packages/jpmml_evaluator/__init__.py in evaluateAll(self, arguments_df, nan_as_missing)
    129                         result_records = self.backend.staticInvoke("org.jpmml.evaluator.python.PythonUtil", "evaluateAll", self.javaEvaluator, argument_records)
    130                 except Exception as e:
--> 131                         raise self.backend.toJavaError(e)
    132                 result_records = self.backend.loads(result_records)
    133                 return DataFrame.from_records(result_records)

JavaError: org.jpmml.evaluator.MissingArgumentException: Function "lessOrEqual" cannot accept missing value at position 0
```

My code for handling characteristics ExpressionTransformer looks like the following,
```
(['d1_under15s_called_opst_phone_cnt_rt'],ExpressionTransformer("-0.0841221664964877 if X[0] <= 0.0 else 0.19635799403181606 if X[0] <= 0.333 else 0.21592881028435115 if X[0] <= 0.5 else 0.33643433273608353 if X[0] <= 0.667 else 0.3116312513399116 if X[0] <= 1.0 else -0.25089876669559863"))
```

Why can't it handle missing values?

**Comment by liuhuanshuo** [comment]
While you were off the line, I looked through many related issues

I think it might be the need to add a ContinuousDomain before ExpressionTransformer?

But even though I did this, it didn't work. Some strange errors occurred.
```
The value of 'sklearn2pmml.decoration.ContinuousDomain.data_min_' attribute (null) is not a supported array type
```

I think the question again comes up over ExpressionTransformer

**Comment by liuhuanshuo** [comment]
The other thing I want to show you is that my data, they're all floats, some of them are NaN(np.nan)

And this data, which contains Nans, works fine in Python

**Comment by liuhuanshuo** [comment]
[I found some clues and ideas in a conversation you had in 19 years](https://groups.google.com/g/jpmml/c/JNGNEXKmd-o/m/lX4XNUVXAwAJ), and I think the final solution should be adding a ContinuousDomain before ExpressionTransformer to handle the missing value in advance, but I seem to be unable to know how to solve it

**Comment by vruusmann** [comment]
> The following error occurs when making a prediction using jpmml-evaluator in Python.

The `MissingArgumentException` is the correct/expected behaviour.

> It seems that the prompt cannot handle missing value, but it is indeed predictable in my pipeline.

Your pipeline "encodes" missing values using `numpy.NaN` numeric constant, whereas (J)PMML pipeline uses a `None` value there. Of course they will behave differently!

Your pipeline:
```python
x = float("NaN")
print(x < 0) # False
print(x > 0) # False
print(x == 0) # False
print(x == x) # False
```

Does the above make any sense? No matter which comparison operator you are using, the result is still `False`. Including the comparison against itself, `x == x`.

(J)PMML pipeline:
```python
x = None
print(x < 0) # TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

Totally makes sense!

> My raw data does contain missing values, and I processed it using ExpressionTransformer. Do I need to add additional processing so that the missing values can be supported by evaluator?

Convert your data matrix - use a column type that supports **_nullable_** float values, and then replace all `numpy.NaN` values with `None` values, and you shall get identical behaviour on all environments.

The `ExpressionTransformer` class has two attributes `map_missing_to` and `default_value`, which can be used to return a predefined scalar value in case any of the expression arguments or the expression evaluation result, respectively, is a (J)PMML missing value.

So, the following should "emulate" Python's non-sensical behaviour:
```python
transformer = ExpressionTransformer("X[0] < 0", map_missing_to = False)
```

**Comment by liuhuanshuo** [comment]
I kept reading your conversations with other people and kept trying, and I finally came up with an answer, and it worked.

Just add this code before ExpressionTransformer
```
ContinuousDomain(with_data=False, with_statistics=False,missing_value_replacement=999)
```

Although I did solve my problem, I still want to know why this can be solved.

with_data=False, with_statistics=False What do these two arguments do?

**Comment by vruusmann** [comment]
> My code for handling characteristics ExpressionTransformer looks like the following...

Let's be clear - your code is NOT handling missing values (`None`); it is handling a special constant (`numpy.NaN`), which is a totally different entity.

> I think it might be the need to add a ContinuousDomain before ExpressionTransformer?

Domain decorator classes (eg. `CategoricalDomain` and `ContinuousDomain`) are meant to define the "model schema" - making a contract, about which data the model is willing to accept from the outside world (eg. are missing values allowed or not). They are not meant to be used withing the model, for performing ordinary data transformations.

> And this data, which contains Nans, works fine in Python

The `numpy.NaN` value is a special constant according to IEEE 754 standard: https://en.wikipedia.org/wiki/IEEE_754

Additionally, see this: https://en.wikipedia.org/wiki/NaN

Quote: "In computing, NaN, standing for Not a Number, is a member of a numeric data type that can be interpreted as a value that is undefined or unrepresentable"

The fact that Scikit-Learn/Python ecosystem is systematically misusing it (as a placeholder for `None`), does not change its true character.
